server:
  port: 8081
  
  
spring:
  application:
    name: emp-service
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/training
    username: root
    password: root 
