server:
  port: 8081
  
  
spring:
  application:
    name: emp-service
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: http://localhost:9411
#  config:
#    import: optional:configserver:http://localhost:8888/
    
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/training
    username: root
    password: root 
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#app:
#   datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://localhost:3306/training
#    username: root
#    password: root 

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"