server:
  port: 9081
  
spring:
  application:
    name: dept-service
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/training
    username: root
    password: root 
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: http://localhost:9411
        
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"