server:
  port: 9088
  
spring:
  application:
    name: hr-service
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: http://localhost:9411 
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
      
resilience4j.circuitbreaker:
    instances:
         appBackend:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
